# Generated by Django 3.1.7 on 2021-03-31 12:30

import cartographer.utils.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformCloudAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', cartographer.utils.db.fields.EncryptedCharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformCloudOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartographer.terraformcloudapikey')),
            ],
        ),
        migrations.RemoveField(
            model_name='terraformproject',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='TerraformProject',
        ),
    ]
