# Generated by Django 3.1.7 on 2021-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0002_auto_20210331_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformcloudorganization',
            name='refreshing',
            field=models.BooleanField(default=False),
        ),
    ]
