# Generated by Django 4.0.5 on 2022-07-05 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0003_terraformcloudorganization_refreshing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSyncJobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default=False, max_length=64)),
                ('total_workspaces', models.IntegerField(default=0)),
            ],
        ),
    ]
