# Generated by Django 4.0.5 on 2022-07-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0004_organizationsyncjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsyncjobs',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartographer.terraformcloudorganization'),
        ),
    ]
