# Generated by Django 4.0.5 on 2022-07-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0005_organizationsyncjobs_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationSyncJobs',
            new_name='OrganizationSyncJob',
        ),
    ]
