# Generated by Django 4.0.5 on 2022-07-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographer', '0006_rename_organizationsyncjobs_organizationsyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsyncjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsyncjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
