name: Security check - Bandit

on: push

jobs:
  bandit-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['pypy-3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Create Env
        run: pip install virtualenv && virtualenv venv

      - name: Activate Env
        run: . venv/bin/activate & echo $(python --version)

      - name: Install Dependencies
        run: pip install -r requirements.txt --upgrade pip
      
      - name: Install Bandit
        run: pip install bandit
  
      - name: Run Bandit
        run: bandit -r terradactyl/ -f json -o bandit-report.json

      - name: Check and Upload Results
        run: |
          RESULTS_LENGTH=$(cat bandit-report.json | jq '.results' | jq length)
          if [ "$RESULTS_LENGTH" -eq "0" ]; then
            echo "Checks passed."
          else
            echo "Bandit found one or more issues. See results."
            exit 1
          fi
          - uses: actions/upload-artifact@v2
        uses: actions/upload-artifact@v2
        with:
          name: bandit-results
          path: bandit-results.json